### ISSUE TITLE
Revanced Youtube is just start buffering after 15-20 seconds

### ISSUE THREAD

**Issue by CasioDuro** [revancedapps/revanced.net#20]
Revanced Youtube is just start buffering after 15-20 seconds and that's it, stopped working, I have tried so many solution, I have tried other versions and microg updates and clear data/cache etc,etc, but no luck, Please help me out !!!!

**Comment by fordiy** [comment]
![image](https://github.com/revancedapps/revanced.net/assets/2220214/14dcc695-3bed-463b-819f-009c23a3849d)
打开spoof client问题就解决了，我也是找了很久，由于Google判断不到正常的user agent引起的。
Enable the spoof client solved the problem, I also spent a long time trying to find the solution. It caused by Google couldn't recognize the normal user agent.
