### ISSUE TITLE
Add S*** from xManager?

### ISSUE THREAD

**Issue by Glazami** [revancedapps/revanced.net#8]
https://github.com/Team-xManager/xManager

**Comment by revancedapps** [comment]
You're right, you have a keen eye for noticing that, but I won't publicly discuss it. The reason is the same as why xManager doesn't mention the term 'S***' in their public repository. xManager uses this link for automatic updates: https://gist.githubusercontent.com/xC3FFF0E/5268182b9bc89832a9cfbe2eb0568c3c. I realized it's the best version of S***, so I've updated it in the Manager app. Everyone can compare the file hash if they feel it's unsafe. I'll close this topic in a few hours to avoid sensitive issues with S****.
